In [1]:
import pandas as pd
import numpy as np

In [2]:
## Download the Data

In [3]:
df_crc=pd.read_csv("./CRC.csv")
df_crc["campus"]="crc"
df_carc=pd.read_csv("./CARC.csv")
df_carc["campus"]="carc"
df_cbzrc=pd.read_csv("./CBZRC.csv")
df_cbzrc["campus"]="cbzrc"
df_clc=pd.read_csv("./CLC.csv")
df_clc["campus"]="clc"
df_cvc=pd.read_csv("./CVC.csv")
df_cvc["campus"]="cvc"
df_evc=pd.read_csv("./EVC.csv")
df_evc["campus"]="evc"
df_irc=pd.read_csv("./IRC.csv")
df_irc["campus"]="irc"
df_smc=pd.read_csv("./SMC.csv")
df_smc["campus"]="smc"
df_src=pd.read_csv("./SRC.csv")
df_src["campus"]="src"
df_wvc=pd.read_csv("./WVC.csv")
df_wvc["campus"]="wvc"
df_main=pd.read_csv("./MAIN.csv")
df_main["campus"]="main"

## raw data

In [4]:
df_crc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 14 columns):
 #   Column                                                                                                              Non-Null Count  Dtype 
---  ------                                                                                                              --------------  ----- 
 0   Timestamp                                                                                                           58 non-null     object
 1   LAST NAME (ALL CAPS) - OPTIONAL                                                                                     17 non-null     object
 2   FIRST NAME (ALL CAPS)  - OPTIONAL                                                                                   12 non-null     object
 3   Did you pass the UPCA?                                                                                              58 non-null     object
 4   In which course did you pass

In [5]:
#cleaning main separately because they used a different format
df_main

Timestamp                      Email Address  \
0    7/15/2021 12:16:21      b21.jeremy.bansil@pshs.edu.ph   
1    7/15/2021 12:16:22    b21.bethena.balanon@pshs.edu.ph   
2    7/15/2021 12:16:32       b21.alex.gagalac@pshs.edu.ph   
3    7/15/2021 12:16:37         b21.harvey.tan@pshs.edu.ph   
4    7/15/2021 12:16:38      b21.eliana.regala@pshs.edu.ph   
..                  ...                                ...   
186   7/16/2021 9:41:06  b21.michelle.sanmateo@pshs.edu.ph   
187  7/16/2021 11:39:29       b21.kevin.tejada@pshs.edu.ph   
188  7/16/2021 18:29:34      b21.zairah.taloma@pshs.edu.ph   
189  7/16/2021 18:36:58       b21.bemas.cabida@pshs.edu.ph   
190  7/16/2021 19:09:41    b21.ernestina.tagle@pshs.edu.ph   

    UP College Admission Status (CAMPUS) UP College Admission Status (COURSE)  \
0                Accepted - First Choice              Accepted - First Choice   
1                Accepted - First Choice              Accepted - First Choice   
2                Accepted - First Choice              Accepted - First Choice   
3                Accepted - First Choice              Accepted - Third Choice   
4                Accepted - First Choice              Accepted - First Choice   
..                                   ...                                  ...   
186                         Not Accepted                                  NaN   
187              Accepted - First Choice              Accepted - First Choice   
188              Accepted - First Choice              Accepted - Third Choice   
189              Accepted - First Choice             Accepted - Second Choice   
190                         Not Accepted                                  NaN   

    Accepted Campus (e.g. UPD, UPM, UPLB)  \
0                                     UPD   
1                                     UPD   
2                                     UPD   
3                                     UPD   
4                                     UPD   
..                                    ...   
186                                   NaN   
187                                   UPM   
188                                   UPD   
189                                   UPD   
190                                   NaN   

    Accepted Course (e.g. BS Computer Science, BS Public Health, BS Psychology)  \
0                                   BS Food Technology                            
1                              BS Chemical Engineering                            
2              BS Molecular Biology and Biotechnology                             
3                             BS Materials Engineering                            
4                                        BS Psychology                            
..                                                 ...                            
186                                                NaN                            
187                                   BS Public Health                            
188                           BS Materials Engineering                            
189                            Electronics Engineering                            
190                                                NaN                            

                    Concerns/Questions?  \
0                                   NaN   
1           None. God bless our batch 🥺   
2                                   NaN   
3                                   NaN   
4    Hugs to those who didn't pass <333   
..                                  ...   
186                                 NaN   
187                                 NaN   
188                                 NaN   
189                                 NaN   
190                                 NaN   

     How many course choices did you indicate in your FORM 1 for your FIRST CHOICE campus?  \
0                                                  NaN                                       
1                                                  Na

In [6]:
df_main["UP College Admission Status (COURSE)"]

0       Accepted - First Choice
1       Accepted - First Choice
2       Accepted - First Choice
3       Accepted - Third Choice
4       Accepted - First Choice
                 ...           
186                         NaN
187     Accepted - First Choice
188     Accepted - Third Choice
189    Accepted - Second Choice
190                         NaN
Name: UP College Admission Status (COURSE), Length: 191, dtype: object

In [7]:
def getCampusStatus(df):
    combined=df["UP College Admission Status (CAMPUS)"]
    return combined.split(" - ")[0]


In [8]:
def getCampusChoice(df):
    combined=df["UP College Admission Status (CAMPUS)"]
    split=combined.split(" - ")
    if(len(split)>1):
        return combined.split(" - ")[1]
    return np.nan
    


In [9]:
def getCourseChoice(df):
    if(df["UP College Admission Status (COURSE)"] is np.nan):
        return np.nan
    combined=df["UP College Admission Status (COURSE)"]
    return combined.split(" - ")[1]

In [10]:
df_main["Did you pass the UPCA? "]=df_main.apply(getCampusStatus,axis=1)
df_main["In which course did you pass? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)"]=df_main["Accepted Course (e.g. BS Computer Science, BS Public Health, BS Psychology)"]
df_main["In which campus?"]=df_main["Accepted Campus (e.g. UPD, UPM, UPLB)"]
df_main["Is it your first campus choice?"]=df_main.apply(getCampusChoice,axis=1)
df_main["My above course is my ___ choice."]=df_main.apply(getCourseChoice,axis=1)
df_main


Timestamp                      Email Address  \
0    7/15/2021 12:16:21      b21.jeremy.bansil@pshs.edu.ph   
1    7/15/2021 12:16:22    b21.bethena.balanon@pshs.edu.ph   
2    7/15/2021 12:16:32       b21.alex.gagalac@pshs.edu.ph   
3    7/15/2021 12:16:37         b21.harvey.tan@pshs.edu.ph   
4    7/15/2021 12:16:38      b21.eliana.regala@pshs.edu.ph   
..                  ...                                ...   
186   7/16/2021 9:41:06  b21.michelle.sanmateo@pshs.edu.ph   
187  7/16/2021 11:39:29       b21.kevin.tejada@pshs.edu.ph   
188  7/16/2021 18:29:34      b21.zairah.taloma@pshs.edu.ph   
189  7/16/2021 18:36:58       b21.bemas.cabida@pshs.edu.ph   
190  7/16/2021 19:09:41    b21.ernestina.tagle@pshs.edu.ph   

    UP College Admission Status (CAMPUS) UP College Admission Status (COURSE)  \
0                Accepted - First Choice              Accepted - First Choice   
1                Accepted - First Choice              Accepted - First Choice   
2                Accepted - First Choice              Accepted - First Choice   
3                Accepted - First Choice              Accepted - Third Choice   
4                Accepted - First Choice              Accepted - First Choice   
..                                   ...                                  ...   
186                         Not Accepted                                  NaN   
187              Accepted - First Choice              Accepted - First Choice   
188              Accepted - First Choice              Accepted - Third Choice   
189              Accepted - First Choice             Accepted - Second Choice   
190                         Not Accepted                                  NaN   

    Accepted Campus (e.g. UPD, UPM, UPLB)  \
0                                     UPD   
1                                     UPD   
2                                     UPD   
3                                     UPD   
4                                     UPD   
..                                    ...   
186                                   NaN   
187                                   UPM   
188                                   UPD   
189                                   UPD   
190                                   NaN   

    Accepted Course (e.g. BS Computer Science, BS Public Health, BS Psychology)  \
0                                   BS Food Technology                            
1                              BS Chemical Engineering                            
2              BS Molecular Biology and Biotechnology                             
3                             BS Materials Engineering                            
4                                        BS Psychology                            
..                                                 ...                            
186                                                NaN                            
187                                   BS Public Health                            
188                           BS Materials Engineering                            
189                            Electronics Engineering                            
190                                                NaN                            

                    Concerns/Questions?  \
0                                   NaN   
1           None. God bless our batch 🥺   
2                                   NaN   
3                                   NaN   
4    Hugs to those who didn't pass <333   
..                                  ...   
186                                 NaN   
187                                 NaN   
188                                 NaN   
189                                 NaN   
190                                 NaN   

     How many course choices did you indicate in your FORM 1 for your FIRST CHOICE campus?  \
0                                                  NaN                                       
1                                                  Na

In [11]:
#dropping the older columns that was replaced and other columns only present in the main data
df_main=df_main.drop(columns=["UP College Admission Status (CAMPUS)","UP College Admission Status (COURSE)","Accepted Campus (e.g. UPD, UPM, UPLB)",
                      "Accepted Course (e.g. BS Computer Science, BS Public Health, BS Psychology)","Email Address","How many course choices did you indicate in your FORM 1 for your FIRST CHOICE campus?",
                     "How many course choices did you indicate in your FORM 1 for your SECOND CHOICE campus?","Concerns/Questions?"])

In [12]:
df_main

Timestamp campus Did you pass the UPCA?   \
0    7/15/2021 12:16:21   main                Accepted   
1    7/15/2021 12:16:22   main                Accepted   
2    7/15/2021 12:16:32   main                Accepted   
3    7/15/2021 12:16:37   main                Accepted   
4    7/15/2021 12:16:38   main                Accepted   
..                  ...    ...                     ...   
186   7/16/2021 9:41:06   main            Not Accepted   
187  7/16/2021 11:39:29   main                Accepted   
188  7/16/2021 18:29:34   main                Accepted   
189  7/16/2021 18:36:58   main                Accepted   
190  7/16/2021 19:09:41   main            Not Accepted   

    In which course did you pass? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)  \
0                                   BS Food Technology                                                             
1                              BS Chemical Engineering                                                             
2              BS Molecular Biology and Biotechnology                                                              
3                             BS Materials Engineering                                                             
4                                        BS Psychology                                                             
..                                                 ...                                                             
186                                                NaN                                                             
187                                   BS Public Health                                                             
188                           BS Materials Engineering                                                             
189                            Electronics Engineering                                                             
190                                                NaN                                                             

    In which campus? Is it your first campus choice?  \
0                UPD                    First Choice   
1                UPD                    First Choice   
2                UPD                    First Choice   
3                UPD                    First Choice   
4                UPD                    First Choice   
..               ...                             ...   
186              NaN                             NaN   
187              UPM                    First Choice   
188              UPD                    First Choice   
189              UPD                    First Choice   
190              NaN                             NaN   

    My above course is my ___ choice.  
0                        First Choice  
1                        First Choice  
2                        First Choice  
3                        Third Choice  
4                        First Choice  
..                                ...  
186                               NaN  
187                      First Choice  
188                      Third Choice  
189                     Second Choice  
190                               NaN  

[191 rows x 7 columns]

In [13]:
#final dataframe by merging all the csv
df_raw=pd.concat([df_crc,df_cbzrc, df_clc,df_cvc,df_evc,df_carc,df_irc,df_smc,df_src,df_wvc,df_main])

In [14]:
#knowing df data
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 190
Data columns (total 24 columns):
 #   Column                                                                                                              Non-Null Count  Dtype 
---  ------                                                                                                              --------------  ----- 
 0   Timestamp                                                                                                           888 non-null    object
 1   LAST NAME (ALL CAPS) - OPTIONAL                                                                                     67 non-null     object
 2   FIRST NAME (ALL CAPS)  - OPTIONAL                                                                                   32 non-null     object
 3   Did you pass the UPCA?                                                                                              890 non-null    object
 4   In which course did you pa

In [15]:
df_raw.describe()

Timestamp LAST NAME (ALL CAPS) - OPTIONAL  \
count                  888                              67   
unique                 868                              65   
top     7/15/2021 20:20:58                          MARTIN   
freq                     2                               2   

       FIRST NAME (ALL CAPS)  - OPTIONAL Did you pass the UPCA?   \
count                                 32                     890   
unique                                32                       7   
top                               DANIKA                      No   
freq                                   1                     337   

       In which course did you pass? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)  \
count                                                 407                                                             
unique                                                152                                                             
top                                   BS COMPUTER SCIENCE                                                             
freq                                                   22                                                             

       My above course is my ___ choice. In which campus?  \
count                                404              419   
unique                                 9               23   
top                           1st Degree       UP DILIMAN   
freq                                 174              111   

       Is it your first campus choice? Will you pursue UP?  \
count                              425                 277   
unique                               4                   7   
top                                Yes                 yes   
freq                               174                  85   

       If not, then at what University do you plan to study?  ...  \
count                                                  96     ...   
unique                                                 52     ...   
top                                                  ADMU     ...   
freq                                                   15     ...   

                       Email Address LAST NAME (ALL CAPS)  \
count                            221                  312   
unique                           221                  293   
top     pdleonoras@cbzrc.pshs.edu.ph               FLORES   
freq                               1                    3   

       FIRST NAME (ALL CAPS) LAST NAME (ALL CAPS)  LAST NAME - optional  \
count                    340                    28                   15   
unique                   339                    28                   15   
top                   CEDRIC               VILARAY              Caranzo   
freq                       2                     1                    1   

       FIRST NAME - optional FIRST NAME (ALL CAPS) - OPTIONAL  \
count                     11                               23   
unique                    11                               23   
top             Mark Russell                    LUCKY JENIÑA    
freq                       1                                1   

            Email address LAST NAME (ALL CAPS, OPTIONAL)  \
count                  90                             13   
unique                 73                             13   
top     sjonyle@gmail.com                        INSIGNE   
freq                   18                              1   

       FIRST NAME (ALL CAPS, OPTIONAL)  
count                               13  
unique                              13  
top                           FRANCINE  
freq                                 1  

[4 rows x 24 columns]

In [16]:
df_raw.head()

Timestamp LAST NAME (ALL CAPS) - OPTIONAL  \
0  7/15/2021 18:07:31                        SOBERANO   
1  7/15/2021 18:07:43                            RUIZ   
2  7/15/2021 18:07:46                             NaN   
3  7/15/2021 18:07:49                             NaN   
4  7/15/2021 18:08:09                             NaN   

  FIRST NAME (ALL CAPS)  - OPTIONAL Did you pass the UPCA?   \
0                            DANIKA                      No   
1                               NaN                      No   
2                               NaN                      No   
3                               NaN                      No   
4                               NaN                      No   

  In which course did you pass? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)  \
0                                                NaN                                                             
1                                                NaN                                                             
2                                                NaN                                                             
3                                                NaN                                                             
4                                                NaN                                                             

  My above course is my ___ choice. In which campus?  \
0                               NaN              NaN   
1                               NaN              NaN   
2                               NaN              NaN   
3                               NaN              NaN   
4                               NaN              NaN   

  Is it your first campus choice? Will you pursue UP?  \
0                             NaN                 NaN   
1                             NaN                 NaN   
2                             NaN                 NaN   
3                             NaN                 NaN   
4                             NaN                 NaN   

  If not, then at what University do you plan to study?  ... Email Address  \
0                                                NaN     ...           NaN   
1                                                NaN     ...           NaN   
2                                                NaN     ...           NaN   
3                                                NaN     ...           NaN   
4                                                NaN     ...           NaN   

  LAST NAME (ALL CAPS) FIRST NAME (ALL CAPS) LAST NAME (ALL CAPS)   \
0                  NaN                   NaN                   NaN   
1                  NaN                   NaN                   NaN   
2                  NaN                   NaN                   NaN   
3                  NaN                   NaN                   NaN   
4                  NaN                   NaN                   NaN   

  LAST NAME - optional FIRST NAME - optional FIRST NAME (ALL CAPS) - OPTIONAL  \
0                  NaN                   NaN                              NaN   
1                  NaN                   NaN                              NaN   
2                  NaN                   NaN                              NaN   
3                  NaN                   NaN                              NaN   
4                  NaN                   NaN                              NaN   

  Email address LAST NAME (ALL CAPS, OPTIONAL) FIRST NAME (ALL CAPS, OPTIONAL)  
0           NaN                            NaN                             NaN  
1           NaN                            NaN                             NaN  
2           NaN                            NaN                             NaN  
3           NaN                            NaN                             NaN  
4           NaN                            NaN                             NaN  

[5 rows x 24 columns]

In [17]:
#count how many null values per column
df_raw.isna().sum().sort_values(ascending=False)

FIRST NAME - optional                                                                                                 880
FIRST NAME (ALL CAPS, OPTIONAL)                                                                                       878
LAST NAME (ALL CAPS, OPTIONAL)                                                                                        878
LAST NAME - optional                                                                                                  876
In which course are you waitlisted? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)    874
In what campus?                                                                                                       874
FIRST NAME (ALL CAPS) - OPTIONAL                                                                                      868
LAST NAME (ALL CAPS)                                                                                                  863
FIRST NAME (ALL CAPS)  -

### dropping columns we dont like

In [18]:
df_drop=df_raw.drop(columns=['LAST NAME (ALL CAPS) ',"LAST NAME (ALL CAPS)","FIRST NAME - optional","LAST NAME - optional","FIRST NAME (ALL CAPS) - OPTIONAL","LAST NAME (ALL CAPS)","FIRST NAME (ALL CAPS)  - OPTIONAL",
                    "LAST NAME (ALL CAPS) - OPTIONAL","Email address","Email Address","LAST NAME (ALL CAPS)","FIRST NAME (ALL CAPS)","Timestamp",'LAST NAME (ALL CAPS, OPTIONAL)', 'FIRST NAME (ALL CAPS, OPTIONAL)'])

#count how many null values per column
df_drop.isna().sum().sort_values(ascending=False)

### renaming columns

In [19]:
df_drop.columns

Index(['Did you pass the UPCA? ',
       'In which course did you pass? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)',
       'My above course is my ___ choice.', 'In which campus?',
       'Is it your first campus choice?', 'Will you pursue UP?',
       'If not, then at what University do you plan to study?',
       'In which course are you waitlisted? (kindy fill-in the exact name of the course as seen in the letter in ALL CAPS)',
       'In what campus?', 'In what campus?.1', 'campus'],
      dtype='object')

In [20]:
df_drop.columns=["app_status","pass_course","pass_courseDegreeChoice","pass_campus","pass_campusFirstChoice","pass_pursue","pass_otherUniversity","waitlist_course","waitlist_campus","dpwas_campus","campus"]

In [21]:
df_drop.columns

Index(['app_status', 'pass_course', 'pass_courseDegreeChoice', 'pass_campus',
       'pass_campusFirstChoice', 'pass_pursue', 'pass_otherUniversity',
       'waitlist_course', 'waitlist_campus', 'dpwas_campus', 'campus'],
      dtype='object')

## Cleaning rows

### App Status Cleaning

In [22]:
#initial status for values in status
df_drop.app_status.unique()

array(['No', 'Yes',
       'DPWAS (learn more at: https://www.reddit.com/r/peyups/comments/b8hqbl/help_what_is_dpwas/)',
       'Waitlisted', nan, 'DPWAS', 'Accepted', 'Not Accepted'],
      dtype=object)

In [23]:
#There is a nan value so it is time to remove them
df_drop=df_drop[df_drop["app_status"].notna()]

In [24]:
#Rename the DPWAS duplicate into just DPWAS
df_drop['app_status']=df_drop['app_status'].str.replace("DPWAS (learn more at: https://www.reddit.com/r/peyups/comments/b8hqbl/help_what_is_dpwas/)","DPWAS",regex=False)
df_drop['app_status']=df_drop['app_status'].str.replace("Not Accepted","No",regex=False)
df_drop['app_status']=df_drop['app_status'].str.replace("Accepted","Yes",regex=False)

In [25]:
#final status for values in status
df_drop.app_status.unique()

array(['No', 'Yes', 'DPWAS', 'Waitlisted'], dtype=object)

In [26]:
#Checking if nothing happened to the values
df_drop.app_status.value_counts()

Yes           405
No            380
DPWAS          88
Waitlisted     17
Name: app_status, dtype: int64

### Pass Course Cleaning

In [27]:
#intial status for values in pass course
df_drop.pass_course.unique()

array([nan, 'BS ARCHITECTURE',
       'UP LOS BANOS, BS AGRICULTURAL BIOTECHNOLOGY',
       'AGRICULTURAL BIOTECHNOLOGY', 'BS STATISTICS', 'BS ECONOMICS',
       'BS Biology', 'BS AGRICULTURAL AND BIOSYSTEMS ENGINEERING',
       'BS BIOLOGY', 'BS APPLIED PHYSICS', 'BS CHEMICAL ENGINEERING ',
       'BS NUTRITION', 'BS MATHEMATICS AND SCIENCE TEACHING',
       'BS COMPUTER ENGINEERING', 'BS PHYSICS', 'D VETERINARY MEDICINE',
       'BS MECHANICAL ENGINEERING ',
       'BS MOLECULAR BIOLOGY AND BIOTECHNOLOGY',
       'BS ELECTRONICS ENGINEERING', 'MECHANICAL ENGINEERING',
       'BS COMPUTER SCIENCE', 'BS CHEMICAL ENGINEERING', 'BS GEOLOGY',
       'BS BIOCHEMISTRY', 'BS CHemistry',
       'BS AGRIBUSINESS MANAGEMENT AND ENTREPRENEURSHIP', 'BS CHEMISTRY',
       'BS Industrial Engineering', 'BS OCCUPATIONAL THERAPY',
       'BS Electrical Engineering', 'BS CIVIL ENGINEERING',
       'BS PUBLIC HEALTH', 'BS MECHANICAL ENGINEERING',
       'BS PHARMACEUTICAL SCIENCES', 'ELECTRONICS ENGINEE

In [38]:

#Lets rename duplicating courses
df_drop["pass_course"]=df_drop["pass_course"].replace([" BS COMPUTER SCIENCE","Computer Science", "BS Computer Science","COMPUTER SCIENCE","BS COMPUTER SCIENCE "],"BS COMPUTER SCIENCE",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["(WAITLISTED) BS AGRICULTURAL AND BIOSYSTEMS ENGINEERING","AGRICULTURAL & BIOSYSTEMS ENGINEERING","BS AGRICULTURAL & BIOSYSTEMS ENGINEERING"],"BS AGRICULTURAL AND BIOSYSTEMS ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["AGRICULTURAL BIOTECHNOLOGY","BS AGRICULTURAL BIOTECHNOLOGY "],"BS AGRICULTURAL BIOTECHNOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["AGRICULTURE"],"BS AGRICULTURE",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["Applied Mathematics"],"BS APPLIED MATHEMATICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["Architecture","BS ARCHITECTURE ","BS architecture"],"BS ARCHITECTURE",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["B FINE ARTS"],"BA FINE ARTS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["WAITLISTED - BS BIO","BS Bio","BACHELOR OF SCIENCE IN BIOLOGY", "BS - BIOLOGY","Biology","BS Biology"],"BS BIOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS  - ELECTRONICS ENGINEERING","BS ELECTRONICS ENGINEERING ","BS Electronics Engineering","ELECTRONICS ENGINEERING"],"BS ELECTRONICS ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["UP LOS BANOS, BS AGRICULTURAL BIOTECHNOLOGY"],"BS AGRICULTURAL BIOTECHNOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["D VETERINARY MEDICINE","VETERINARY MEDICINE (8TH CHOICE)","VETERINARY MEDICINE"],"BS VETERINARY MEDICINE",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS CHemistry","BS Chemistry"],"BS CHEMISTRY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS Industrial Engineering"],"BS INDUSTRIAL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS ELECTRICAL ENGG","BS Electrical Engineering"],"BS ELECTRICAL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["FOOD SCIENCE","FOOD TECHNOLOGY","BS FOOD SCIENCE AND TECHNOLOGY", "BS Food Technology","BS Food Technology "],"BS FOOD TECHNOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS Metallurgical Engineering"],"BS METALLURGICAL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS PHARMACY (5 YRS)","BS PHARMACY","BS PHARMACEUTICAL SCIENCES (5 YRS)","Pharmaceutical Sciences ","PHARMACEUTICAL SCIENCES","BS PHARMACEUTICAL SCIENCES "],"BS PHARMACEUTICAL SCIENCES",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["UP LOS BANOS, BS APPLIED PHYSICS"],"BS APPLIED PHYSICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS AGRICULTURAL CHEMISTRY ","Los Baños- Agricultural Chemistry"],"BS AGRICULTURAL CHEMISTRY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS AGRIBUSINESS ECONOMICS "],"BS AGRIBUSINESS ECONOMICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS Computer Engineering "],"BS COMPUTER ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS BUSINESS ADMINISTRATION & ACCOUNTANCY","BS Business Administration"],"BS BUSINESS ADMINISTRATION",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS Materials Engineering","MATERIALS ENGINEERING"],"BS MATERIALS ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS MECH ENGG","MECHANICAL ENGINEERING","BS MECHANICAL ENGINEERING "],"BS MECHANICAL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["CHEMICAL ENGINEERING","BS CHEMICAL ENGINEERING ","CHEMICAL ENGINEERING "],"BS CHEMICAL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["NUTRITION"],"BS NUTRITION",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["PUBLIC HEALTH","Public Health"],"BS PUBLIC HEALTH",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["ECONOMICS"],"BS ECONOMICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS in Fisheries"],"BS FISHERIES",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["OCCUPATIONAL THERAPY"],"BS OCCUPATIONAL THERAPY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS AGRIBUSINESS MANAGEMENT AND ENTREPRENEURSHIP "],"BS AGRIBUSINESS MANAGEMENT AND ENTREPRENEURSHIP",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS STATISTICS "],"BS STATISTICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS MATHEMATICS "],"BS MATHEMATICS",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BA PSYCHOLOGY - APPLIED PSYCHOLOGY"],"BA PSYCHOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS CIVIL ENGINEERING "],"BS CIVIL ENGINEERING",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["BS MBB","BS MBB ","BS MOLECULAR BIOLOGY AND BIOTECHNOLOGY "],"BS MOLECULAR BIOLOGY AND BIOTECHNOLOGY",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["B SPORTS SCIENCE"],"BS SPORTS SCIENCE",regex=False)

#Upper Case All Courses
df_drop["pass_course"]=df_drop["pass_course"].str.upper()


In [39]:
#final status for values in pass_course
df_drop["pass_course"].unique()

array([nan, 'BS ARCHITECTURE', 'BS AGRICULTURAL BIOTECHNOLOGY',
       'BS STATISTICS', 'BS ECONOMICS', 'BS BIOLOGY',
       'BS AGRICULTURAL AND BIOSYSTEMS ENGINEERING', 'BS APPLIED PHYSICS',
       'BS CHEMICAL ENGINEERING', 'BS NUTRITION',
       'BS MATHEMATICS AND SCIENCE TEACHING', 'BS COMPUTER ENGINEERING',
       'BS PHYSICS', 'BS VETERINARY MEDICINE',
       'BS MECHANICAL ENGINEERING',
       'BS MOLECULAR BIOLOGY AND BIOTECHNOLOGY',
       'BS ELECTRONICS ENGINEERING', 'BS COMPUTER SCIENCE', 'BS GEOLOGY',
       'BS BIOCHEMISTRY', 'BS CHEMISTRY',
       'BS AGRIBUSINESS MANAGEMENT AND ENTREPRENEURSHIP',
       'BS INDUSTRIAL ENGINEERING', 'BS OCCUPATIONAL THERAPY',
       'BS ELECTRICAL ENGINEERING', 'BS CIVIL ENGINEERING',
       'BS PUBLIC HEALTH', 'BS PHARMACEUTICAL SCIENCES', 'BS GEOGRAPHY',
       'BS MATHEMATICS', 'BS METALLURGICAL ENGINEERING',
       'BS FOOD TECHNOLOGY', 'BS MATERIALS ENGINEERING',
       'BS FAMILY LIFE AND CHILD DEVELOPMENT', 'BS FISHERIES',
     

In [40]:
#checking that nothing with wrong in data
df_drop["pass_course"].value_counts()

BS BIOLOGY                 37
BS COMPUTER SCIENCE        36
BS CHEMICAL ENGINEERING    29
BS FOOD TECHNOLOGY         24
BS PUBLIC HEALTH           23
                           ..
BA FINE ARTS                1
BS HOME ECONOMICS           1
BS HUMAN ECOLOGY            1
BA POLITICAL SCIENCE        1
N/A                         1
Name: pass_course, Length: 61, dtype: int64

### Pass Course Degree Choice Cleaning

In [41]:
#initial status for pass_course
df_drop["pass_courseDegreeChoice"].unique()

array([nan, '1st Degree', '4th Degree', '3rd Degree', '5th Degree',
       '2nd Degree', 'First Choice', 'Third Choice', 'Fourth Choice',
       'Second Choice'], dtype=object)

In [42]:
#Rename Columns
df_drop["pass_course"]=df_drop["pass_course"].replace(["First Choice"],"1st Degree",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["Second Choice"],"2nd Degree",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["Third Choice"],"3rd Degree",regex=False)
df_drop["pass_course"]=df_drop["pass_course"].replace(["Fourth Choice"],"4th Degree",regex=False)

### Pass Campus Cleaning

In [43]:
#initial status of pass_campus
df_drop["pass_campus"].unique()

array([nan, 'UP MINDANAO', 'UP LOS BANOS', 'UP ILOILO', 'UP VISAYAS',
       'UP DILIMAN', 'UP MANILA', 'UP BAGUIO', 'Tacloban', 'TACLOBAN',
       'UP TACLOBAN', 'BAGUIO', 'UP VISAYAS-ILOILO', 'UP Cebu', 'UPD',
       'UPM', 'UPLB', 'UPDEPP', 'UP Diliman', 'Los Banos', 'UP Los Banos',
       'None', 'UPB', 'N/a'], dtype=object)

In [46]:
#replacing satellite campuses with their autonomous campus
df_drop["pass_campus"]=df_drop["pass_campus"].replace(["UPV","UP VISAYAS-ILOILO","UP ILOILO","Tacloban","TACLOBAN","UP TACLOBAN"],"UP VISAYAS", regex=False)
df_drop["pass_campus"]=df_drop["pass_campus"].replace(["BAGUIO"],"UP BAGUIO", regex=False)
df_drop["pass_campus"]=df_drop["pass_campus"].replace(["UPD","UPDEPP","UP Diliman"],"UP DILIMAN", regex=False)
df_drop["pass_campus"]=df_drop["pass_campus"].replace(["UPM"],"UP MANILA", regex=False)
df_drop["pass_campus"]=df_drop["pass_campus"].replace(["UP Los Banos","Los Banos","UPB"],"UP LOS BANOS", regex=False)

In [47]:
#final status of pass_campus
df_drop["pass_campus"].unique()

array([nan, 'UP MINDANAO', 'UP LOS BANOS', 'UP VISAYAS', 'UP DILIMAN',
       'UP MANILA', 'UP BAGUIO', 'UP CEBU', 'UPLB', 'None', 'N/a'],
      dtype=object)

In [48]:
#checking that data is fine
df_drop["pass_campus"].value_counts()

UP DILIMAN      208
UP LOS BANOS     60
UP MANILA        55
UP VISAYAS       51
UPLB             18
UP MINDANAO      15
UP BAGUIO         8
None              2
UP CEBU           1
N/a               1
Name: pass_campus, dtype: int64

### Pass Campus First Choice Cleaning

In [50]:
#initial status for pass_campusFirstChoice
df_drop.pass_campusFirstChoice.unique()

array([nan, 'No', 'Yes', 'First Choice', 'Second Choice'], dtype=object)

In [51]:
#renaming duplicate data
df_drop["pass_campusFirstChoice"]=df_drop["pass_campusFirstChoice"].str.replace("First Choice","Yes")
df_drop["pass_campusFirstChoice"]=df_drop["pass_campusFirstChoice"].str.replace("Second Choice","No")

In [53]:
#final status for pass_campusFirstChoice
df_drop.pass_campusFirstChoice.unique()

array([nan, 'No', 'Yes'], dtype=object)

### Pass Pursue Cleaning

In [54]:
#initial status for pass pursue
df_drop.pass_pursue.unique()

array([nan, 'yes', 'no', 'not sure', 'Yes', 'Unsure', 'No', 'Not sure'],
      dtype=object)

In [55]:
#renaming duplicate data
df_drop["pass_pursue"]=df_drop["pass_pursue"].replace(["Yes"],"yes",regex=False)
df_drop["pass_pursue"]=df_drop["pass_pursue"].replace(["No"],"no",regex=False)
df_drop["pass_pursue"]=df_drop["pass_pursue"].replace(["Unsure","Not sure"],"not sure",regex=False)

In [56]:
#final status for pass pursue
df_drop.pass_pursue.unique()

array([nan, 'yes', 'no', 'not sure'], dtype=object)

### Pass Other University Cleaning

In [57]:
df_drop.columns

Index(['app_status', 'pass_course', 'pass_courseDegreeChoice', 'pass_campus',
       'pass_campusFirstChoice', 'pass_pursue', 'pass_otherUniversity',
       'waitlist_course', 'waitlist_campus', 'dpwas_campus', 'campus'],
      dtype='object')

In [58]:
df_drop["pass_otherUniversity"].unique()

array([nan, 'dlsu', 'ADMU', 'DE LA SALLE UNIVERSITY or VELEZ COLLEGE',
       'PHILIPPINE STATE COLLEGE OF AERONAUTICS',
       'Ateneo de Manila University', 'Ateneo De Manila University',
       'DLSU', 'De La Salle University', 'University of Santo Tomas',
       'Maybe Ateneo', 'AUF (Angeles University Foundation)',
       'University of Santo Tomas (UST)', 'IDK', 'dlsu maybe?',
       'NOT SURE', '--', 'Visayas State University', 'DLSU Manila',
       'admu', 'La Salle', 'De La Salle University (DLSU)',
       'DLSU, Velez College',
       'Philippine State College of Aeronautics(if admitted)',
       "I will pursue UP if they allow me to transfer to UPB Com Sci. If they don't allow the transfer and I don't pass on the DOST Scholarship, I will pursue my course and campus. If they don't allow the transfer but I pass the DOST Scholarship, I will go to SLU to study Electrical Engineering.  ",
       'SAINT LOUIS UNIVERSITY BAGUIO CITY', 'MAPUA', 'none',
       'SLU BAGUIO', 'UST', 'N

In [59]:
#remove repeating responses
df_drop["pass_otherUniversity"]=df_drop["pass_otherUniversity"].replace(["dlsu","DE LA SALLE UNIVERSITY or VELEZ COLLEGE","DLSU","De La Salle University","dlsu maybe?","DLSU Manila",
                                                                        "La Salle","De La Salle University (DLSU)","DLSU, Velez College"],"DE LA SALLE UNIVERSITY",regex=False)
df_drop["pass_otherUniversity"]=df_drop["pass_otherUniversity"].replace(["ADMU","Ateneo de Manila University","Ateneo De Manila University","Maybe Ateneo","admu"],"ATENEO DE MANILA UNIVERSITY",regex=False)

### Waitlist Course Cleaning

In [60]:
#intial status of waitlist course
df_drop["waitlist_course"].unique()

array([nan, 'BS APPLIED MATHEMATICS', 'BS BIOLOGY', 'BS BIOCHEMISTRY',
       'BS SPEECH PATHOLOGY', 'BACHELOR OF SCIENCE IN BIOLOGY',
       'BS PUBLIC HEALTH', 'BS Math', 'FOOD TECH',
       'BS PHARMACEUTICAL SCIENCES', 'BS CHEMISTRY', 'BS FOOD TECHNOLOGY',
       'BS Applied Physics', 'BA PSYCHOLOGY'], dtype=object)

In [61]:
#removing some duplicates
df_drop["waitlist_course"]=df_drop["waitlist_course"].replace(["FOOD TECH"],"BS FOOD TECHNOLOGY")
df_drop["waitlist_course"]=df_drop["waitlist_course"].replace(["BACHELOR OF SCIENCE IN BIOLOGY"],"BS BIOLOGY")
df_drop["waitlist_course"]=df_drop["waitlist_course"].replace(["BS Math"],"BS MATH")
df_drop["waitlist_course"]=df_drop["waitlist_course"].replace(["BS Applied Physics"],"BS APPLIED PHYSICS")

In [62]:
#final status of waitlist course
df_drop["waitlist_course"].unique()

array([nan, 'BS APPLIED MATHEMATICS', 'BS BIOLOGY', 'BS BIOCHEMISTRY',
       'BS SPEECH PATHOLOGY', 'BS PUBLIC HEALTH', 'BS MATH',
       'BS FOOD TECHNOLOGY', 'BS PHARMACEUTICAL SCIENCES', 'BS CHEMISTRY',
       'BS APPLIED PHYSICS', 'BA PSYCHOLOGY'], dtype=object)

### Waitlist Course Cleaning

In [63]:
df_drop.columns

Index(['app_status', 'pass_course', 'pass_courseDegreeChoice', 'pass_campus',
       'pass_campusFirstChoice', 'pass_pursue', 'pass_otherUniversity',
       'waitlist_course', 'waitlist_campus', 'dpwas_campus', 'campus'],
      dtype='object')

In [64]:
#intial status of waitlist campus, already clean
df_drop["waitlist_campus"].unique()

array([nan, 'UP MINDANAO', 'UP CEBU', 'UP MANILA', 'UP VISAYAS',
       'UP BAGUIO', 'UP LOS BANOS'], dtype=object)

### Dpwas Course Cleaning

In [65]:
df_drop.columns

Index(['app_status', 'pass_course', 'pass_courseDegreeChoice', 'pass_campus',
       'pass_campusFirstChoice', 'pass_pursue', 'pass_otherUniversity',
       'waitlist_course', 'waitlist_campus', 'dpwas_campus', 'campus'],
      dtype='object')

In [66]:
#intial status of waitlist campus, already clean
df_drop["dpwas_campus"].unique()

array([nan, 'UP VISAYAS', 'UP ILOILO', 'UP MINDANAO', 'UP LOS BANOS',
       'UP DILIMAN', 'UP MANILA', 'UP BAGUIO'], dtype=object)

In [67]:
## Saving Cleaned dataframe to CSV

In [68]:
df_drop.to_csv("UPCA_cleaned.csv",index=False)